// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjaamacqvcswiggfbqhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqYWFtYWNxdmNzd2lnZ2ZicWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNzUxNzgsImV4cCI6MjA1MDg1MTE3OH0.dmbs5oxEudPxJK5nsJHGrMXm_XfVqSYWygSqB1xoC10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);